### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by alexnedelcu** [alexplumb/material-ui-phone-number#15]
I am using SSR and I am getting the following error:

ReferenceError: window is not defined
at Object. (D:\dev\myproject\node_modules\material-ui-phone-number\dist\index.js:1:1601)
at Module._compile (module.js:652:30)
at Module._extensions..js (module.js:663:10)
at Object.require.extensions.(anonymous function) [as .js] (D:\dev\peerleap\node_modules\babel-register\lib\node.js:152:7)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)

**Comment by alexnedelcu** [comment]
This is because server side rendering has no knowledge of window. I am not sure what causes "window" to show up in the distributed file, as I did not find it in source..

**Comment by alexplumb** [comment]
Thanks for the heads-up, @alexnedelcu. Can you tell me which version you're using?

**Comment by epribula** [comment]
Hey, I am facing the same issue with version 1.6.1

**Comment by alexplumb** [comment]
This should be fixed in v2.0.0 - this was caused by a bug with webpack: https://github.com/webpack/webpack/issues/6525

**Comment by romikette** [comment]
I am using nextjs 8.1.0 and it still crashes with: 

ReferenceError: window is not defined
at r (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:83774)
at i (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:83862)
at n.exports (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:87435)
at Object.<anonymous> (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:70404)
  at t (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:1869)
  at Module.<anonymous> (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:92052)
    at t (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:1869)
    at D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:2668
    at D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:2679
    at e (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:143)
    at Object.<anonymous> (D:\work\myProject\ui\node_modules\material-ui-phone-number\dist\index.js:1:1686)
      at Module._compile (module.js:653:30)
      at Object.Module._extensions..js (module.js:664:10)
      at Module.load (module.js:566:32)
      at tryModuleLoad (module.js:506:12)
      at Function.Module._load (module.js:498:3)


I got it working like this:

import dynamic from 'next/dynamic';
const MuiPhoneNumber=dynamic(import ('material-ui-phone-number'),{ssr:false});

**Comment by alexplumb** [comment]
@romikette Are you using webpack to build your project? Can you try wrapping MuiPhoneNumber in `<NoSSR>`?

https://material-ui.com/components/no-ssr/

**Comment by comxd** [comment]
Using NextJS, wrapping MuiPhoneNumber in <NoSsr> not working.

**Comment by di1606** [comment]
but now do you know how to use adapt the module on nextjs with typecript?
